// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "codegen": {
    "Manager": {
      /**
       * CodeGenerate
       * @param {ConfigContext} arg1 - Go Type: *codegen.ConfigContext
       * @returns {Promise<string|Error>}  - Go Type: string
       */
      "CodeGenerate": (arg1) => {
        return window.go.codegen.Manager.CodeGenerate(arg1);
      },
    },
  },

  "main": {
    "App": {
      /**
       * Execute
       * @param {ConfigContext} arg1 - Go Type: codegen.ConfigContext
       * @returns {Promise<string|Error>}  - Go Type: string
       */
      "Execute": (arg1) => {
        return window.go.main.App.Execute(arg1);
      },
      /**
       * GetOs
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetOs": () => {
        return window.go.main.App.GetOs();
      },
      /**
       * Greet
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Greet": (arg1) => {
        return window.go.main.App.Greet(arg1);
      },
      /**
       * PingDb
       * @param {DataSourceConfig} arg1 - Go Type: codegen.DataSourceConfig
       * @returns {Promise<Array<DatabaseOptions>|Error>}  - Go Type: []codegen.DatabaseOptions
       */
      "PingDb": (arg1) => {
        return window.go.main.App.PingDb(arg1);
      },
    },
  },

};
export default go;
